services:
  - type: web
    name: yg-photoshop-academy
    env: node
    region: singapore
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: yg-photoshop-academy-jwt-secret-key-2026
      - key: JWT_EXPIRATION
        value: 7d
      - key: DATABASE_URL
        value: file:./dev.db
